config/routes.rb
Kr::Application.routes.draw do
  resources :posts

  root :to => 'reports#index'

  resources :reports

  match 'search' => 'reports#search'
  match 'tagged/:tag' => 'reports#tagged', :as => :tagged_report, :via => :get

  match '/settings/edit', to: 'settings#edit', :as => :edit_setting, :via => :get
  match '/settings/update', to: 'settings#update', :as => :update_setting, :via => :put

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/posts/add_new_comment' => 'posts#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]

  resources :posts do
    resources :comments
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user, :bypass => true
      redirect_to edit_setting_path
    else
      render 'edit'
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/settings/edit.html.erb
<div class='page-header'>
  <h3>프로필 설정</h3>
</div>

<%= form_for @user, :url => update_setting_path, :html => { :multipart => true } do |f| %>

  <%= render 'error_messages' %>

  <ul class='thumbnails'>
    <li class='span3'>
      <div class='thumbnail'>
        <%= image_tag @user.avatar.url(:thumb) %>
        <%= f.file_field :avatar %>
      </div>
          <table class='table'>
          <tbody>
            <tr>
              <td>이메일:</td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <td>회원권한:</td>
              <td>5</td>
            </tr>
            <tr>
              <td>포인트:</td>
              <td>2985 점</td>
            </tr>
            <tr>
              <td>회원가입일:</td>
              <td>2011-12-08</td>
            </tr>
            <tr>
              <td>최종접속일:</td>
              <td>2012-07-25 10:58:30</td>
          </tbody>
          </table>
    </li>
  </ul>

  <%= f.submit "변경사항 저장하기", class: "btn btn-primary" %>

<% end %>