config/routes.rb
Kr::Application.routes.draw do
  resources :posts

  root :to => 'reports#index'

  resources :reports

  match 'search' => 'reports#search'
  match 'tagged/:tag' => 'reports#tagged', :as => :tagged_report, :via => :get

  match '/settings/edit', to: 'settings#edit', :as => :edit_setting, :via => :get
  match '/settings/update', to: 'settings#update', :as => :update_setting, :via => :put

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/posts/add_new_comment' => 'posts#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]

  resources :posts do
    resources :comments
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :title, :document, :tag_list

  belongs_to :user

  has_attached_file :document

  acts_as_ordered_taggable

  validates :title, :presence => true, :length => { :minimum => 2 }

  validates_attachment :document, :presence => true,
    :size => { :in => 0..9999.kilobytes }

  default_scope :order => 'reports.id DESC'

  def self.text_search( query )
    if query.present?
      where("title like :q", q: "%#{query}%")
    else
      scoped
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:index, :search]

  def search
    @reports = Report.text_search(params[:query])
    @tags = Report.tag_counts_on(:tags)
  end

  def tagged
    @reports = Report.tagged_with(params[:tag])
    @tags = Report.tag_counts_on(:tags)
    render :action => :search
  end

  def show
    @report = Report.find(params[:id])
    render :action => :show
  end

  def edit
    @report = Report.find_by_id(params[:id])
    if @report.nil?
      redirect_to :action => :index
    end
    if @report.user_id != current_user.id
      redirect_to :action => :index
    end
  end

  def update
    @report = Report.find_by_id(params[:id])

    respond_to do |format|
      if @report.user_id == current_user.id && @report.update_attributes(params[:report])
        format.html { redirect_to edit_report_path, notice: 'Report was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def index
    if user_signed_in?
      @reports = Report.paginate :page => params[:page], :per_page => 18, :conditions => ['user_id =?', current_user.id]

      session[:page] = params[:page]

      @tags = Report.tag_counts_on(:tags)
    else
      redirect_to new_user_registration_path
    end
  end

  def new
    @report = Report.new
  end

  def create
    @user = User.find_by_id(current_user.id)
    @report = @user.reports.build(params[:report])

    if @report.save
      flash[:notice] = "Report was successfully uploaded."
      redirect_to reports_path
    else
      flash[:error] = "Error."
      redirect_to new_report_path
    end
  end

  def destroy
    @report = Report.find_by_id(params[:id])

    if @report.user_id == current_user.id && @report.destroy
      flash[:notice] = "Report was successfully deleted."
    else
      flash[:error] = "Error."
    end
    
    redirect_to reports_path(@report, { :page => session[:page] })
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  include ActsAsTaggableOn::TagsHelper

  def report_file_extension( report )
    if report && report.document_file_name && report.document_file_name.match(/\./)
      split = report.document_file_name.split(".")
      if split
        extension = split.last
        if extension
          return extension.upcase
        end
      end
    end
    return "Unknown"
  end

  def avatar_url( user_id)
    user = User.find_by_id(user_id)
    if user
      return user.avatar.url(:thumb)
    else
      return ""
    end
  end

  def email( user_id )
    user = User.find_by_id(user_id)
    if user
      return user.email
    else
      return ""
    end
  end
end

app/views/reports/_disqus.html.erb
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'koreport'; // required: replace example with your forum shortname
            var disqus_url = window.location.href;

            disqus_url = disqus_url.replace(/\/edit$/, "");

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        

app/views/reports/_error_messages.html.erb
<% if @report.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@report.errors.count, "error") %>.
		</div>
		<ul>
		<% @report.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/reports/_tag_cloud.html.erb
<% if params[:controller] == 'reports' && (params[:action] == 'index' || params[:action] == 'search' || params[:action] == 'tagged') && @tags %>
  태그들
  <div id='tag_cloud'>
    <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, '/tagged/' + tag.name, :class => css_class %>
    <% end %>
  </div>
<% else %>
<% end %>

app/views/reports/_tag_list.html.erb
<% report.tag_list.each do |tag| %>
  <%= link_to "/tagged/" + tag, :class => 'post-tag' do %>
  <%= tag %>
  <% end %>
<% end %>

app/views/reports/edit.html.erb
<h2>리포트 수정</h2>

<%= form_for @report, :url => { :action => 'update' }, :html => { :multipart => true } do |f| %>

  <%= render 'error_messages' %>

  <br />

  제목:
  <div class="input-prepend">
    <span class="add-on"><i class="icon-font"></i></span><%= f.text_field :title, :class => 'span4', :placeholder => '리포트 제목' %>
  </div>

  <br />

  포맷: <%= report_file_extension( @report ) %>

  <br />
  <br />

  보기:
  <div>
    <%= link_to '리포트 다운', @report.document.url, :class => 'btn btn-info' %>
  </div>

  <br />

  다른 화일로 새로 업로드:
  <div class="input-prepend">
    <span class="add-on"><i class="icon-upload"></i></span><%= f.file_field :document , :class => 'span4' %>
  </div>

  <br />

  <i class="icon-tags"></i> 관련태그
  <input name="report[tag_list]" id="mytags" value="<%= @report.tag_list %>">

  <br />

  <button type="submit" class="btn btn-primary"><i class="icon-save"></i> 변경사항 저장하기</button>
  <%= link_to :back, :class => 'btn btn-primary' do %>
    &laquo; 뒤로
  <% end %>
  <%= link_to '리포트 지우기', report_path(@report), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>

<% end %>

app/views/reports/index.html.erb
<div class='page-header'>
  <h3>내가 올린 리포트들</h3>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>No</th>
      <th class="span4">제목</th>
      <th>태그</th>
      <th>판매 횟수</th>
      <th>매출</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.id %></td>
        <td class="span4">
          <%= link_to report.title, report_path(report) %>
        </td>
        <td>
          <%= render :partial => 'tag_list', :locals => { :report => report } %>
        </td>
        <td>5</td>
        <td>10,000 원</td>
        <td>
          <span class="btn-group" style="float:right">
            <a class="btn btn-mini downdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> Share<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><i class="icon-twitter"></i> Twitter</a></li>
              <li><a href="#"><i class="icon-facebook"></i> Facebook</a></li>
              <li><a href="#"><i class="icon-pencil"></i> Me2day</a></li>
              <li><a href="#"><i class="icon-envelope"></i> Email</a></li>
            </ul>
          </span>
          <%= link_to '수정', edit_report_path(report), :class => 'btn btn-mini', :style => "float:right" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @reports, :renderer => BootstrapPagination::Rails %>

<%= link_to search_path, :class => 'btn btn-primary' do %>
  리포트 모두 보기 &raquo;
<% end %>

<%= link_to new_report_path, :class => 'btn' do %>
  리포트 등록 &raquo;
<% end %>

app/views/reports/new.html.erb
<h2>리포트 등록</h2>

<%= form_for @report, :url => reports_path, :method => :post, :html => { :multipart => true } do |f| %>

  <%= render 'error_messages' %>

  <br />

  업로드 화일
  <div class="input-prepend">
    <span class="add-on"><i class="icon-file"></i></span><%= f.file_field :document , :class => 'span4' %>
  </div>

  <br />

  리포트 제목
  <div class="input-prepend">
    <span class="add-on"><i class="icon-font"></i></span><%= f.text_field :title, :class => 'span4', :placeholder => '리포트 제목' %>
  </div>

  <br />

  <i class="icon-tags"></i> 관련 태그
  <input name="report[tag_list]" id="mytags" value="<%= @report.tag_list %>"> 

  <br />

  <button type="submit" class="btn btn-primary"><i class="icon-upload"></i> 리포트 등록</button>

<% end %>

app/views/reports/search.html.erb
<div>
  <% if @reports.count == 0 %>
  <h3>Not found</h3>
  <br />
  <% else %>
    <div class='page-header'>
      <h3>검색 결과</h3>
    </div>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>No</th>
          <th class='span4'>제목</th>
          <th>태그</th>
          <th>작성자</th>
          <th>판매 횟수</th>
          <th>가격</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @reports.each do |report| %>
          <tr class='span4'>
            <td><%= report.id %></td>
            <td><%= link_to report.title, report_path(report) %>
            <td>
              <%= render :partial => 'tag_list', :locals => { :report => report } %>
            </td>
            <td><%= email(report.user_id) %></td>
            <td>5</td>
            <td>1,000 원</td>
            <td>
              <% if report.user_id == current_user.id %>
                <%= link_to '수정', edit_report_path(report), :class => 'btn btn-mini' %>
              <% else %>
                <%= link_to '구매', report.document.url, :class => 'btn btn-mini btn-success' %>
              <% end %>
              <%= link_to '이메일', '#', :class => 'btn btn-mini' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <%= link_to :back, :class => 'btn btn-primary' do %>
    &laquo; 뒤로
  <% end %>
</div> 

app/views/reports/show.html.erb
<h2>리포트 보기</h2>

<%= render 'error_messages' %>

<br />

<table class='table'>
<thead>
<th class='span2'>
</th>
<th></th>
</thead>
<tbody>
<tr>
<td>리포트 ID:</td>
<td><%= @report.id %> </td>
</tr>

<tr>
<td>작성자 사진:</td>
<td><%= image_tag avatar_url(@report.user_id) %></td>
</tr>

<tr>
<td>작성자:</td>
<td><%= email(@report.user_id) %></td>
</tr>

<tr>
<td>제목:</td>
<td><%= @report.title %></td>
</tr>

<tr>
<td>포맷:</td>
<td><%= report_file_extension( @report ) %></td>
</tr>

<tr>
<td>태그:</td>
<td><%= render :partial => 'tag_list', :locals => { :report => @report } %></td>
</tr>

<tr>
<td>가격:</td>
<td>1,000 원</td>
</tr>
</tbody>
</table>

<%= link_to '리포트 구매', @report.document.url, :class => 'btn btn-success' %>
<%= link_to :back, :class => 'btn btn-primary' do %>
  &laquo; 뒤로
<% end %>

<br />
<br />

<%= render 'disqus' %>