config/routes.rb
Kr::Application.routes.draw do
  resources :posts

  root :to => 'reports#index'

  resources :reports

  match 'search' => 'reports#search'
  match 'tagged/:tag' => 'reports#tagged', :as => :tagged_report, :via => :get

  match '/settings/edit', to: 'settings#edit', :as => :edit_setting, :via => :get
  match '/settings/update', to: 'settings#update', :as => :update_setting, :via => :put

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match '/posts/add_new_comment' => 'posts#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]

  resources :posts do
    resources :comments
  end
end

app/views/layouts/_debug.html.erb
<div class="row">
  <div class="span12">
    <%= debug(params) %>
    <%= debug(current_user) %>
    <%= debug(request.fullpath) %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="alert fade in">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong><%= msg %></strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
      <ul class="nav pull-left">
        <li style="padding:7px"><%= link_to "Home", "/" %></li>
        <li style="padding:7px"><%= link_to "개인정보취급방침", '#' %></li>
        <li style="padding:7px"><%= link_to "이용약관", '#' %></li>
        <li style="padding:7px"><%= link_to "책임한계와법적고지", '#' %></li>
        <li style="padding:7px">(주)코리포트 - 서울특별시 광진구 자양동 (대표이사: 홍길동)</li>
      </ul>
      <ul class="nav pull-right">
        <li><%= link_to image_tag("twitter_32.png", :border => 0), "http://twitter.com/koreport", :target => "_blank" %></li>
        <li><%= link_to image_tag("facebook_32.png", :border => 0), "http://facebook.com/koreport", :target => "_blank" %></li>
      </ul>

<!--
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
  </script>

  <a href="https://twitter.com/koreport" class="twitter-follow-button" data-show-count="false">Follow @koreport</a>
-->
<% if false %>
  <%= render 'layouts/debug' %>
<% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner" style="font-size:14px;">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">koReport BETA</a>
      <div class="nav-collapse">
        <ul class="nav" style="padding-top:10px;"> 
          <li>하드디스크에서 잠자는 리포트를 팔아라!<li>
        </ul>
      </div>
      <div class="nav-collapse pull-right">
        <% if user_signed_in? %>
          <ul class="nav">
            <li>
              <%= form_tag search_path, method: :get, class: 'navbar-search form-inline', name: 'search-form' do %>
                <%= text_field_tag :query, params[:query], class: 'search-query', placeholder: '리포트 제목을 입력하세요' %>
                <input type=submit value="Search" class='search-query'>
              <% end %>
            </li>
            <li>
              <%= link_to reports_path do %>
                <i class='icon-dashboard'></i> 대쉬보드
              <% end %>
            </li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user icon-large"></i> <%= current_user.email %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_setting_path do %>
                    <i class="icon-user icon-large"></i> 프로필 설정
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="icon-lock icon-large"></i> 보안 설정
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to '#' do %>
                    <i class="icon-money icon-large"></i> 출금 계좌 설정
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="icon-off icon-large"></i> 로그아웃
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        <% else %>
          <ul class="nav">
            <li style="padding-top:10px;">계정이 있으신가요? &#160</li>
            <li><%= link_to "로그인", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidenav.html.erb
<div class='sidebar-nav'>
  <ul class='nav nav-list'>
  <% if user_signed_in? %>
    <li>
      <%= image_tag current_user.avatar.url(:thumb) %>
    </li>
    <li>
      <%= current_user.email %>님
    </li>
    <li>
      등급: 절대상인(Lvl.37)
    </li>
    <li>
      &nbsp;
    </li>
  <% end %>
  <li>
    <%= link_to reports_path do %>
      <i class='icon-dashboard'></i> 대쉬보드
    <% end %>
  </li>
  <li>
    <div id="noticeModal" class="modal hide fade">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h3><i class='icon-exclamation-sign'></i> 공지</h3>
      </div>
      <div class="modal-body">
      <h4>결제모듈관련</h4>
      <br />
      <p>고객여러분 안녕하십니까.</p>
      <p>지금 통장 입금을 통한 결제 플로우를 구현중입니다.</p>
      <p>불편하시더라도 조금만 참아주십시요.</p>
      <p>앞으로도 최선을 다하는 코리포트가 되겠습니다.</p>
      <p>2012 년 7 월 12 일</p>
      <p>코리포트 일동</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
    <a data-toggle="modal" href="#noticeModal" class="">
      <i class='icon-exclamation-sign'></i> 공지
    </a>
  </li>
  <li>
    <%= link_to '#', :class => '' do %>
      <i class='icon-search'></i> 검색
    <% end %>
  </li>
  <li>
    <%= link_to posts_path, :class => '' do %>
      <i class='icon-heart'></i> 질문게시판
    <% end %>
  <li>
    <%= link_to posts_path, :class => '' do %>
      <i class='icon-book'></i> 자료요청게시판
    <% end %>
  </li>
  </ul>
</div>

app/views/layouts/_ticker.html.erb
<div>
  <table class='table table-bordered'>
    <tbody>
      <tr>
        <td>동시접속자:</td>
        <td>128</td>
      </tr>
      <tr>
        <td>등록자료수:</td>
        <td>5,482</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>좋은 리포트, koReport - 쉽고 빠르게 검색하고 바로 다운받으세요</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class="row">
    <div class='span2'>
      <%= render 'layouts/sidenav' %>
    </div>
    <div class="span8">
    <%= render :partial => 'layouts/flash', object: flash %>
    <%= yield %>
    </div>
    <div class='span2'>
      <%= render :partial => 'layouts/ticker' %>
      <%= render :partial => 'reports/tag_cloud' %>
    </div>
  </div>

  <%= render 'layouts/footer' %>
<!--
  <%= render 'layouts/debug' %>
  -->
</div>

</body>
</html>